import { Appointment } from "../features/appointmentSlice";


export const fakeAppointments: Appointment[] = [
    {
      id: "1",
      doctorId: "doc1",
      patientId: "patient1",
      doctorName: "Dr. Smith",
      patientName: "John Doe",
      time: new Date("2023-01-10T09:00:00"),
      status: "ACCEPT",
      note: "Regular checkup",
    },
    {
      id: "2",
      doctorId: "doc2",
      patientId: "patient2",
      doctorName: "Dr. Johnson",
      patientName: "Jane Doe",
      time: new Date("2023-01-12T14:30:00"),
      status: "REJECT",
      note: "Follow-up appointment",
    },
    {
      id: "3",
      doctorId: "doc3",
      patientId: "patient3",
      doctorName: "Dr. Anderson",
      patientName: "Bob Smith",
      time: new Date("2023-01-15T11:45:00"),
      status: "PENDING",
      note: "Dental checkup",
    },
    {
      id: "4",
      doctorId: "doc4",
      patientId: "patient4",
      doctorName: "Dr. Brown",
      patientName: "Alice Johnson",
      time: new Date("2023-01-18T08:30:00"),
      status: "REJECT",
      note: "Emergency visit",
    },
    {
      id: "5",
      doctorId: "doc5",
      patientId: "patient5",
      doctorName: "Dr. Wilson",
      patientName: "Eva Davis",
      time: new Date("2023-01-20T16:15:00"),
      status: "ACCEPT",
      note: "Eye examination",
    },
    {
      id: "6",
      doctorId: "doc6",
      patientId: "patient6",
      doctorName: "Dr. Taylor",
      patientName: "Chris Brown",
      time: new Date("2023-01-22T10:30:00"),
      status: "ACCEPT",
      note: "Physical checkup",
    },
    {
      id: "7",
      doctorId: "doc7",
      patientId: "patient7",
      doctorName: "Dr. White",
      patientName: "Olivia Taylor",
      time: new Date("2023-01-25T13:45:00"),
      status: "ACCEPT",
      note: "Vaccination",
    },
    {
      id: "8",
      doctorId: "doc8",
      patientId: "patient8",
      doctorName: "Dr. Miller",
      patientName: "Samuel Wilson",
      time: new Date("2023-01-28T12:00:00"),
      status: "REJECT",
      note: "Blood test",
    },
    {
      id: "9",
      doctorId: "doc9",
      patientId: "patient9",
      doctorName: "Dr. Lee",
      patientName: "Sophia Miller",
      time: new Date("2023-01-30T15:20:00"),
      status: "PENDING",
      note: "Urgent appointment",
    },
    {
      id: "10",
      doctorId: "doc10",
      patientId: "patient10",
      doctorName: "Dr. Hall",
      patientName: "Liam Lee",
      time: new Date("2023-02-02T17:30:00"),
      status: "PENDING",
      note: "Allergy consultation",
    },
  ];